# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: dark-mode
spec:
  enabled: false
  requires: ">=2.25.0"
  author:
    name: LHY
    website: https://github.com/LHY0125
  logo: logo.png
  homepage: https://github.com/LHY0125/halo-dark-mode-plugin#readme
  repo: https://github.com/LHY0125/halo-dark-mode-plugin
  issues: https://github.com/LHY0125/halo-dark-mode-plugin/issues
  displayName: "深色模式"
  description: "为 Halo 后台管理面板提供深色/浅色模式切换，支持跟随系统、手动切换和偏好记忆"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/LHY0125/halo-dark-mode-plugin/blob/main/LICENSE"
